### ISSUE TITLE
Logo Proposal for Active

### ISSUE THREAD

**Issue by leonardoderoy** [TiagoMaiaL/Active#1]
Hello! @TiagoMaiaL

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards
Leonardo Deroy 

Graphic Designer

**Comment by TiagoMaiaL** [comment]
Hello @leonardoderoy 

I'd be really glad to have your help with this project's logo. I'm still working on the storage layer, but I'll be soon working on the main screens of the app, and having a logo would help me in this process, not to mention that I'm not experienced in designing logos.

**Comment by leonardoderoy** [comment]
Hellow @TiagoMaiaL  Excellent I would like to know what your project is about and the exact name would be very useful

**Comment by TiagoMaiaL** [comment]
The project is about managing and tracking habits. The user adds a new habit and defines the days he'll be trying to accomplish the activity. He also adds the fire dates for the local notifications. These local notifications would ask the user if he accomplished the habit at the specific day. There'll be an initial screen showing the added habits, the progress bar of each one, and the color the user has chosen for the habit. I'm also planning to add a calendar view to show the executed activities per day, so the user could tap and see what was executed on a specific day. I'll be modifying the project's README, but there's some information there as well.

Regarding the name: It's a very generic one yet, but I'm planning (not completely sure though) to use Active in the name, maybe with another word better describing the app.

**Comment by leonardoderoy** [comment]
this is my proposal I can modify what you want
![image](https://user-images.githubusercontent.com/40496274/42255433-b5404f9c-7f19-11e8-9306-0be56769541c.png)

**Comment by TiagoMaiaL** [comment]
Hey @leonardoderoy , thanks for providing me with the options and great job. I was thinking about it and what do you think of removing the "active" name and using a tick (similar to the one provided in the 7th option) or a more general symbol as the logo? I came to this conclusion because I'm not sure about the app's name yet, and I also think a more general symbol would fit better since the user can add a habit related to anything he wants.

I'm still selecting the colors for the UI and finishing the wireframes for this first version, and as soon as I select them, I will post them here so we can elaborate a better concept based on those colors as well.

Sorry for the late response, thank you for your work.
